<a href="https://colab.research.google.com/github/WongChinWee/RepoTaughtbyDrAqilla/blob/main/Copy_of_Untitled39.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Churn_Modelling_ HasCrCard.csv')

dataset

,RowNumber,CustomerId,First Name,Second Name,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,IsActiveMember,EstimatedSalary,HasCrCard
0,1,15634602,Ella,Elsa,619,Pahang,Female,42,2,0.00,1,1,101348.88,1
1,2,15647311,Hiza,Hiza,608,Johor,Female,41,1,83807.86,1,1,112542.58,0
2,3,15619304,Mila,Fiza,502,Kelantan,Female,42,8,159660.80,3,0,113931.57,1
3,4,15701354,Tia,Salma,699,Johor,Female,39,1,0.00,2,0,93826.63,0
4,5,15737888,Nisha,Rose,850,Selangor,Female,43,2,125510.82,1,1,79084.10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Syamsul,Ramli,771,Selangor,Male,39,5,0.00,2,0,96270.64,1
9996,9997,15569892,Zaid,Umar,516,Selangor,Male,35,10,57369.61,1,1,101699.77,1
9997,9998,15584532,Dwi,Zara,709,Pahang,Female,36,7,0.00,1,1,42085.58,0
9998,9999,15682355,Sadiq,Ramzi,772,Selangor,Male,42,3,75075.31,2,0,92888.52,1
9999,10000,15628319,Asha,Dania,792,Selangor,Female,28,4,130142.79,1,0,38190.78,1

In [ ]:
X = pd.DataFrame(dataset.iloc[:, 3:13].values)
y = dataset.iloc[:, 13].values

X

           0    1         2       3   4   5          6  7  8          9
0       Elsa  619    Pahang  Female  42   2        0.0  1  1  101348.88
1       Hiza  608     Johor  Female  41   1   83807.86  1  1  112542.58
2       Fiza  502  Kelantan  Female  42   8   159660.8  3  0  113931.57
3      Salma  699     Johor  Female  39   1        0.0  2  0   93826.63
4       Rose  850  Selangor  Female  43   2  125510.82  1  1    79084.1
...      ...  ...       ...     ...  ..  ..        ... .. ..        ...
9995  Ramli   771  Selangor    Male  39   5        0.0  2  0   96270.64
9996   Umar   516  Selangor    Male  35  10   57369.61  1  1  101699.77
9997    Zara  709    Pahang  Female  36   7        0.0  1  1   42085.58
9998  Ramzi   772  Selangor    Male  42   3   75075.31  2  0   92888.52
9999   Dania  792  Selangor  Female  28   4  130142.79  1  0   38190.78

[10000 rows x 10 columns]

In [ ]:
y

array([1, 0, 1, ..., 0, 1, 1])

In [ ]:
# prompt: display y in table form

pd.DataFrame(y)

      0
0     1
1     0
2     1
3     0
4     1
...  ..
9995  1
9996  1
9997  0
9998  1
9999  1

[10000 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_2 = LabelEncoder()
X.loc[:, 2] = labelencoder_X_2.fit_transform(X.iloc[:, 2])
X

<ipython-input-8-557108bfa9bb>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.loc[:, 2] = labelencoder_X_2.fit_transform(X.iloc[:, 2])

           0    1  2       3   4   5          6  7  8          9
0       Elsa  619  2  Female  42   2        0.0  1  1  101348.88
1       Hiza  608  0  Female  41   1   83807.86  1  1  112542.58
2       Fiza  502  1  Female  42   8   159660.8  3  0  113931.57
3      Salma  699  0  Female  39   1        0.0  2  0   93826.63
4       Rose  850  3  Female  43   2  125510.82  1  1    79084.1
...      ...  ... ..     ...  ..  ..        ... .. ..        ...
9995  Ramli   771  3    Male  39   5        0.0  2  0   96270.64
9996   Umar   516  3    Male  35  10   57369.61  1  1  101699.77
9997    Zara  709  2  Female  36   7        0.0  1  1   42085.58
9998  Ramzi   772  3    Male  42   3   75075.31  2  0   92888.52
9999   Dania  792  3  Female  28   4  130142.79  1  0   38190.78

[10000 rows x 10 columns]

In [ ]:
labelencoder_X_1 = LabelEncoder()
X.loc[:, 1] = labelencoder_X_1.fit_transform(X.iloc[:, 1])
X

<ipython-input-9-71945c574f01>:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.loc[:, 1] = labelencoder_X_1.fit_transform(X.iloc[:, 1])

           0    1  2       3   4   5          6  7  8          9
0       Elsa  228  2  Female  42   2        0.0  1  1  101348.88
1       Hiza  217  0  Female  41   1   83807.86  1  1  112542.58
2       Fiza  111  1  Female  42   8   159660.8  3  0  113931.57
3      Salma  308  0  Female  39   1        0.0  2  0   93826.63
4       Rose  459  3  Female  43   2  125510.82  1  1    79084.1
...      ...  ... ..     ...  ..  ..        ... .. ..        ...
9995  Ramli   380  3    Male  39   5        0.0  2  0   96270.64
9996   Umar   125  3    Male  35  10   57369.61  1  1  101699.77
9997    Zara  318  2  Female  36   7        0.0  1  1   42085.58
9998  Ramzi   381  3    Male  42   3   75075.31  2  0   92888.52
9999   Dania  401  3  Female  28   4  130142.79  1  0   38190.78

[10000 rows x 10 columns]

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Assuming X is your DataFrame
column_transformer = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [1])  # Apply OneHotEncoder to the second column
    ],
    remainder='passthrough'  # Keep the non-transformed columns
)

X_encoded = column_transformer.fit_transform(X)

# Use LabelEncoder for the first column if needed
labelencoder_X_1 = LabelEncoder()
X_encoded[:, 0] = labelencoder_X_1.fit_transform(X_encoded[:, 0])
ddd = X_encoded[:, 1:]
ddd

ValueError: For a sparse output, all columns should be a numeric or convertible to a numeric.